<?php

use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\ApiDocumentationController;
use App\Http\Controllers\Api\V1\ApiTokenController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BrandingController;
use App\Http\Controllers\Api\V1\BillingController;
use App\Http\Controllers\Api\V1\CustomerController;
use App\Http\Controllers\Api\V1\EmailController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OltController;
use App\Http\Controllers\Api\V1\OltManagementController;
use App\Http\Controllers\Api\V1\OntController;
use App\Http\Controllers\Api\V1\OnuController;
use App\Http\Controllers\Api\V1\PaymongoController;
use App\Http\Controllers\Api\V1\GcashController;
use App\Http\Controllers\Api\V1\PermissionController;
use App\Http\Controllers\Api\V1\RoleController;
use App\Http\Controllers\Api\V1\RouterController;
use App\Http\Controllers\Api\V1\BngController;
use App\Http\Controllers\Api\V1\AcsServerController;
use App\Http\Controllers\Api\V1\ActivationController;
use App\Http\Controllers\Api\V1\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1/auth')->group(function (): void {
    Route::post('login', [AuthController::class, 'login']);
});

Route::prefix('v1')->middleware(['auth:sanctum'])->group(function (): void {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('docs', [ApiDocumentationController::class, 'index']);
    Route::get('api-tokens', [ApiTokenController::class, 'index'])->middleware('permission:api-tokens.view');
    Route::post('api-tokens', [ApiTokenController::class, 'store'])->middleware('permission:api-tokens.create');
    Route::delete('api-tokens/{id}', [ApiTokenController::class, 'destroy'])->middleware('permission:api-tokens.delete');
    Route::get('permissions', [PermissionController::class, 'index'])->middleware('permission:roles.view');
    Route::get('roles', [RoleController::class, 'index'])->middleware('permission:roles.view');
    Route::post('roles', [RoleController::class, 'store'])->middleware('permission:roles.create');
    Route::get('roles/{id}', [RoleController::class, 'show'])->middleware('permission:roles.view');
    Route::put('roles/{id}', [RoleController::class, 'update'])->middleware('permission:roles.update');
    Route::delete('roles/{id}', [RoleController::class, 'destroy'])->middleware('permission:roles.delete');
    Route::get('audit-logs', [AuditLogController::class, 'index']);
    Route::get('branding', [BrandingController::class, 'show'])->middleware('permission:branding.view');
    Route::put('branding', [BrandingController::class, 'update'])->middleware('permission:branding.update');
    Route::get('email', [EmailController::class, 'show'])->middleware('permission:email.view');
    Route::put('email', [EmailController::class, 'update'])->middleware('permission:email.update');
    Route::post('email/test', [EmailController::class, 'test'])->middleware('permission:email.test');
    Route::get('notifications', [NotificationController::class, 'show'])->middleware('permission:notifications.view');
    Route::put('notifications', [NotificationController::class, 'update'])->middleware('permission:notifications.update');
    Route::post('notifications/test', [NotificationController::class, 'test'])->middleware('permission:notifications.test');
    Route::get('paymongo', [PaymongoController::class, 'show'])->middleware('permission:paymongo.view');
    Route::put('paymongo', [PaymongoController::class, 'update'])->middleware('permission:paymongo.update');
    Route::post('paymongo/test', [PaymongoController::class, 'test'])->middleware('permission:paymongo.test');
    Route::post('paymongo/test-payment', [PaymongoController::class, 'testPayment'])->middleware('permission:paymongo.test');
    Route::get('gcash', [GcashController::class, 'show'])->middleware('permission:gcash.view');
    Route::put('gcash', [GcashController::class, 'update'])->middleware('permission:gcash.update');
    Route::get('gcash/payments', [GcashController::class, 'payments'])->middleware('permission:gcash.view');
    Route::get('gcash/invoices', [GcashController::class, 'invoices'])->middleware('permission:gcash.view');
    Route::get('gcash/statements', [GcashController::class, 'statements'])->middleware('permission:gcash.view');
    Route::post('gcash/payments', [GcashController::class, 'store'])->middleware('permission:gcash.create');
    Route::post('gcash/payments/{id}/review', [GcashController::class, 'review'])->middleware('permission:gcash.review');
    Route::get('gcash/payments/{id}/receipt', [GcashController::class, 'receipt'])->middleware('permission:gcash.view');
    Route::get('users', [UserController::class, 'index'])->middleware('permission:users.view');
    Route::post('users', [UserController::class, 'store'])->middleware('permission:users.create');
    Route::get('users/{publicId}', [UserController::class, 'show'])->middleware('permission:users.view');
    Route::put('users/{publicId}', [UserController::class, 'update'])->middleware('permission:users.update');
    Route::delete('users/{publicId}', [UserController::class, 'destroy'])->middleware('permission:users.delete');
    Route::get('customers', [CustomerController::class, 'index'])->middleware('api.ability:customers.view');
    Route::post('customers', [CustomerController::class, 'store'])->middleware('api.ability:customers.create');
    Route::get('customers/{publicId}', [CustomerController::class, 'show'])->middleware('api.ability:customers.view');
    Route::post('customers/{publicId}/reveal-ppp-password', [CustomerController::class, 'revealPppPassword'])->middleware('api.ability:customers.view');
    Route::put('customers/{publicId}', [CustomerController::class, 'update'])->middleware('api.ability:customers.update');
    Route::delete('customers/{publicId}', [CustomerController::class, 'destroy'])->middleware('api.ability:customers.delete');
    Route::get('billing-accounts', [BillingController::class, 'accounts'])->middleware('api.ability:billing-accounts.view');
    Route::post('billing-accounts', [BillingController::class, 'storeAccount'])->middleware('api.ability:billing-accounts.create');
    Route::delete('billing-accounts/{publicId}', [BillingController::class, 'destroyAccount'])->middleware('api.ability:billing-accounts.delete');
    Route::get('plans', [BillingController::class, 'plans'])->middleware('api.ability:plans.view');
    Route::post('plans', [BillingController::class, 'storePlan'])->middleware('api.ability:plans.create');
    Route::put('plans/{id}', [BillingController::class, 'updatePlan'])->middleware('api.ability:plans.update');
    Route::delete('plans/{id}', [BillingController::class, 'destroyPlan'])->middleware('api.ability:plans.delete');
    Route::get('subscriber-services', [BillingController::class, 'services'])->middleware('api.ability:subscriber-services.view');
    Route::post('subscriber-services', [BillingController::class, 'storeService'])->middleware('api.ability:subscriber-services.create');
    Route::get('subscriptions', [BillingController::class, 'subscriptions'])->middleware('api.ability:subscriptions.view');
    Route::post('subscriptions', [BillingController::class, 'storeSubscription'])->middleware('api.ability:subscriptions.create');
    Route::put('subscriptions/{id}', [BillingController::class, 'updateSubscription'])->middleware('api.ability:subscriptions.update');
    Route::delete('subscriptions/{id}', [BillingController::class, 'destroySubscription'])->middleware('api.ability:subscriptions.delete');
    Route::get('activations', [ActivationController::class, 'index'])->middleware('permission:activations.view');
    Route::get('activation-options', [ActivationController::class, 'options'])->middleware('permission:activations.view');
    Route::post('activation-preview', [ActivationController::class, 'preview'])->middleware('permission:activations.create');
    Route::post('activation-presets', [ActivationController::class, 'storePreset'])->middleware('permission:activations.create');
    Route::post('activations', [ActivationController::class, 'store'])->middleware('permission:activations.create');
    Route::post('activations/bulk', [ActivationController::class, 'bulk'])->middleware('permission:activations.create');
    Route::patch('activations/{publicId}/deactivate', [ActivationController::class, 'deactivate'])->middleware('permission:activations.create');
    Route::delete('activations/{publicId}', [ActivationController::class, 'destroy'])->middleware('permission:activations.create');
    Route::get('billing-settings', [BillingController::class, 'billingSettings'])->middleware('api.ability:billing.view');
    Route::put('billing-settings', [BillingController::class, 'updateBillingSettings'])->middleware('api.ability:billing.update');
    Route::get('billing-statements', [BillingController::class, 'statements'])->middleware('api.ability:billing-statements.view');
    Route::post('billing-statements', [BillingController::class, 'generateStatement'])->middleware('api.ability:billing-statements.create');
    Route::delete('billing-statements/{id}', [BillingController::class, 'destroyStatement'])->middleware('api.ability:billing-statements.delete');
    Route::get('routers', [RouterController::class, 'index'])->middleware('permission:routers.view');
    Route::post('routers', [RouterController::class, 'store'])->middleware('permission:routers.create');
    Route::post('routers/test-connection', [RouterController::class, 'testConnection'])->middleware('permission:routers.view');
    Route::post('routers/{publicId}/connect', [RouterController::class, 'connect'])->middleware('permission:routers.update');
    Route::post('routers/{publicId}/disconnect', [RouterController::class, 'disconnect'])->middleware('permission:routers.update');
    Route::get('routers/{publicId}/session-status', [RouterController::class, 'sessionStatus'])->middleware('permission:routers.view');
    Route::get('routers/{publicId}', [RouterController::class, 'show'])->middleware('permission:routers.view');
    Route::put('routers/{publicId}', [RouterController::class, 'update'])->middleware('permission:routers.update');
    Route::delete('routers/{publicId}', [RouterController::class, 'destroy'])->middleware('permission:routers.delete');
    Route::get('acs-servers', [AcsServerController::class, 'index'])->middleware('permission:acs.view');
    Route::post('acs-servers', [AcsServerController::class, 'store'])->middleware('permission:acs.create');
    Route::post('acs-servers/test-ssh', [AcsServerController::class, 'testSsh'])->middleware('permission:acs.test');
    Route::post('acs-servers/test-api', [AcsServerController::class, 'testApi'])->middleware('permission:acs.test');
    Route::get('acs-servers/{publicId}', [AcsServerController::class, 'show'])->middleware('permission:acs.view');
    Route::put('acs-servers/{publicId}', [AcsServerController::class, 'update'])->middleware('permission:acs.update');
    Route::delete('acs-servers/{publicId}', [AcsServerController::class, 'destroy'])->middleware('permission:acs.delete');
    Route::post('acs-servers/{publicId}/test-ssh', [AcsServerController::class, 'testStoredSsh'])->middleware('permission:acs.test');
    Route::post('acs-servers/{publicId}/test-api', [AcsServerController::class, 'testStoredApi'])->middleware('permission:acs.test');
    Route::get('acs-servers/{publicId}/settings/password-complexity', [AcsServerController::class, 'passwordComplexity'])->middleware('permission:acs.update');
    Route::patch('acs-servers/{publicId}/settings/password-complexity', [AcsServerController::class, 'updatePasswordComplexity'])->middleware('permission:acs.update');
    Route::get('bngs', [BngController::class, 'index']);
    Route::post('bngs', [BngController::class, 'store']);
    Route::get('bngs/{publicId}', [BngController::class, 'show']);
    Route::patch('bngs/{publicId}/interfaces', [BngController::class, 'updateInterfaces']);
    Route::get('bngs/{publicId}/vlan-syncs', [BngController::class, 'vlanSyncs']);
    Route::post('bngs/{publicId}/vlan-syncs', [BngController::class, 'storeVlanSync']);
    Route::patch('bngs/{publicId}/vlan-syncs/{syncId}', [BngController::class, 'updateVlanSync']);
    Route::delete('bngs/{publicId}/vlan-syncs/{syncId}', [BngController::class, 'destroyVlanSync']);
    Route::get('bngs/{publicId}/accel-ppp-config', [BngController::class, 'accelPppConfig']);
    Route::post('bngs/{publicId}/accel-ppp-config/preview', [BngController::class, 'previewAccelPppConfig']);
    Route::put('bngs/{publicId}/accel-ppp-config', [BngController::class, 'saveAccelPppConfig']);
    Route::get('bngs/{publicId}/cgnat-policies', [BngController::class, 'cgnatPolicies']);
    Route::post('bngs/{publicId}/cgnat-policies', [BngController::class, 'storeCgnatPolicy']);
    Route::delete('bngs/{publicId}/cgnat-policies/{policyId}', [BngController::class, 'destroyCgnatPolicy']);
    Route::get('bngs/{publicId}/forwarding-rules', [BngController::class, 'forwardingRules']);
    Route::post('bngs/{publicId}/forwarding-rules', [BngController::class, 'storeForwardingRule']);
    Route::delete('bngs/{publicId}/forwarding-rules/{ruleId}', [BngController::class, 'destroyForwardingRule']);
    Route::get('bngs/{publicId}/radius-servers', [BngController::class, 'radiusServers']);
    Route::post('bngs/{publicId}/radius-servers', [BngController::class, 'storeRadiusServer']);
    Route::patch('bngs/{publicId}/radius-servers/{serverId}', [BngController::class, 'updateRadiusServer']);
    Route::post('bngs/{publicId}/radius-servers/test-connection', [BngController::class, 'testRadiusDatabase']);
    Route::delete('bngs/{publicId}/radius-servers/{serverId}', [BngController::class, 'destroyRadiusServer']);
    Route::get('bngs/{publicId}/speed-boosts', [BngController::class, 'speedBoosts']);
    Route::post('bngs/{publicId}/speed-boosts/preview', [BngController::class, 'previewSpeedBoost']);
    Route::post('bngs/{publicId}/speed-boosts', [BngController::class, 'storeSpeedBoost']);
    Route::patch('bngs/{publicId}/speed-boosts/{boostId}', [BngController::class, 'updateSpeedBoost']);
    Route::post('bngs/{publicId}/speed-boosts/{boostId}/apply', [BngController::class, 'applySpeedBoost']);
    Route::delete('bngs/{publicId}/speed-boosts/{boostId}', [BngController::class, 'destroySpeedBoost']);
    Route::post('bngs/{publicId}/iptables/preview', [BngController::class, 'previewIptables']);
    Route::post('bngs/{publicId}/iptables/save', [BngController::class, 'saveIptables']);
    Route::put('bngs/{publicId}', [BngController::class, 'update']);
    Route::delete('bngs/{publicId}', [BngController::class, 'destroy']);
    Route::post('bngs/{publicId}/connect', [BngController::class, 'connect']);
    Route::post('bngs/{publicId}/disconnect', [BngController::class, 'disconnect']);
    Route::get('bngs/{publicId}/session-status', [BngController::class, 'sessionStatus']);
    Route::get('olts', [OltController::class, 'index'])->middleware('permission:olts.view');
    Route::post('olts', [OltController::class, 'store'])->middleware('permission:olts.create');
    Route::post('olts/test-connection', [OltController::class, 'testConnection'])->middleware('permission:olts.view');
    Route::get('olts/{publicId}', [OltController::class, 'show'])->middleware('permission:olts.view');
    Route::put('olts/{publicId}', [OltController::class, 'update'])->middleware('permission:olts.update');
    Route::delete('olts/{publicId}', [OltController::class, 'destroy'])->middleware('permission:olts.delete');
    Route::post('olts/{publicId}/connect', [OltController::class, 'connect'])->middleware('permission:olts.update');
    Route::post('olts/{publicId}/disconnect', [OltController::class, 'disconnect'])->middleware('permission:olts.update');
    Route::get('olts/{publicId}/session-status', [OltController::class, 'sessionStatus'])->middleware('permission:olts.view');
    Route::get('olts/{publicId}/management', [OltManagementController::class, 'show'])->middleware('permission:olts.manage');
    Route::get('olts/{publicId}/terminal-users', [OltManagementController::class, 'terminalUsers'])->middleware('permission:olts.manage');
    Route::patch('olts/{publicId}/terminal-user-policy', [OltManagementController::class, 'updateTerminalUserPolicy'])->middleware('permission:olts.provision');
    Route::get('onts', [OntController::class, 'index'])->middleware('permission:onts.view');
    Route::post('onts/discover', [OntController::class, 'discover'])->middleware('permission:onts.discover');
    Route::get('onts/settings', [OntController::class, 'settings'])->middleware('permission:onts.view');
    Route::patch('onts/settings', [OntController::class, 'updateSettings'])->middleware('permission:onts.update');
    Route::get('onts/acs-servers', [OntController::class, 'acsServers'])->middleware('permission:onts.view');
    Route::post('onts', [OntController::class, 'store'])->middleware('permission:onts.create');
    Route::get('onts/{publicId}/management', [OntController::class, 'management'])->middleware('permission:onts.view');
    Route::post('onts/{publicId}/management/configuration-export', [OntController::class, 'exportConfiguration'])->middleware('permission:onts.view');
    Route::post('onts/{publicId}/management/tasks', [OntController::class, 'managementTask'])->middleware('permission:onts.update');
    Route::get('onts/{publicId}', [OntController::class, 'show'])->middleware('permission:onts.view');
    Route::put('onts/{publicId}', [OntController::class, 'update'])->middleware('permission:onts.update');
    Route::delete('onts/{publicId}', [OntController::class, 'destroy'])->middleware('permission:onts.delete');
    Route::get('onus', [OnuController::class, 'index'])->middleware('permission:onus.view');
    Route::post('onus', [OnuController::class, 'store'])->middleware('permission:onus.create');
    Route::get('onus/{publicId}', [OnuController::class, 'show'])->middleware('permission:onus.view');
    Route::put('onus/{publicId}', [OnuController::class, 'update'])->middleware('permission:onus.update');
    Route::delete('onus/{publicId}', [OnuController::class, 'destroy'])->middleware('permission:onus.delete');
    Route::post('olts/{publicId}/vlans', [OltManagementController::class, 'storeVlan'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/vlans/{id}', [OltManagementController::class, 'updateVlan'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/vlans/{id}', [OltManagementController::class, 'destroyVlan'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/qinq', [OltManagementController::class, 'storeQinq'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/qinq/preview', [OltManagementController::class, 'previewQinq'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/qinq/{id}', [OltManagementController::class, 'updateQinq'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/qinq/{id}', [OltManagementController::class, 'destroyQinq'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/dba-profiles', [OltManagementController::class, 'storeDbaProfile'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/dba-profiles/{id}', [OltManagementController::class, 'destroyDbaProfile'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/ont-service-profiles', [OltManagementController::class, 'storeOntServiceProfile'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/ont-service-profiles/{id}', [OltManagementController::class, 'updateOntServiceProfile'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/ont-service-profiles/{id}', [OltManagementController::class, 'destroyOntServiceProfile'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/ont-wan-profiles', [OltManagementController::class, 'storeOntWanProfile'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/ont-wan-profiles/{id}', [OltManagementController::class, 'updateOntWanProfile'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/ont-wan-profiles/{id}', [OltManagementController::class, 'destroyOntWanProfile'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/ont-tr069-server-profiles', [OltManagementController::class, 'storeOntTr069ServerProfile'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/ont-tr069-server-profiles/{id}', [OltManagementController::class, 'updateOntTr069ServerProfile'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/ont-tr069-server-profiles/{id}', [OltManagementController::class, 'destroyOntTr069ServerProfile'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/dba-profile-settings', [OltManagementController::class, 'updateDbaProfileStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/ont-service-profile-settings', [OltManagementController::class, 'updateOntServiceProfileStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/ont-wan-profile-settings', [OltManagementController::class, 'updateOntWanProfileStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/ont-tr069-profile-settings', [OltManagementController::class, 'updateOntTr069ProfileStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/ont-line-profile-settings', [OltManagementController::class, 'updateOntLineProfileStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/s-vlan-settings', [OltManagementController::class, 'updateSVlanStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/c-vlan-settings', [OltManagementController::class, 'updateCVlanStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/tr069-vlan-settings', [OltManagementController::class, 'updateTr069VlanStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/vlan-settings', [OltManagementController::class, 'updateVlanStart'])->middleware('permission:olts.provision');
    Route::patch('olts/{publicId}/ont-id-capacity-settings', [OltManagementController::class, 'updateOntIdCapacity'])->middleware('permission:olts.provision');
    Route::post('olts/{publicId}/terminal-users', [OltManagementController::class, 'storeTerminalUser'])->middleware('permission:olts.provision');
    Route::put('olts/{publicId}/terminal-users/{id}', [OltManagementController::class, 'updateTerminalUser'])->middleware('permission:olts.provision');
    Route::delete('olts/{publicId}/terminal-users/{id}', [OltManagementController::class, 'destroyTerminalUser'])->middleware('permission:olts.provision');
    Route::get('invoices', [BillingController::class, 'invoices'])->middleware('api.ability:invoices.view');
    Route::post('invoices', [BillingController::class, 'storeInvoice'])->middleware('api.ability:invoices.create');
    Route::get('payments', [BillingController::class, 'payments'])->middleware('api.ability:payments.view');
    Route::post('payments', [BillingController::class, 'storePayment'])->middleware('api.ability:payments.create');
});
