<?php

use App\Http\Controllers\Api\V1\AuditLogController;
use App\Http\Controllers\Api\V1\ApiDocumentationController;
use App\Http\Controllers\Api\V1\ApiTokenController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\BrandingController;
use App\Http\Controllers\Api\V1\BillingController;
use App\Http\Controllers\Api\V1\CustomerController;
use App\Http\Controllers\Api\V1\EmailController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\PaymongoController;
use App\Http\Controllers\Api\V1\GcashController;
use App\Http\Controllers\Api\V1\PermissionController;
use App\Http\Controllers\Api\V1\RoleController;
use App\Http\Controllers\Api\V1\RouterController;
use App\Http\Controllers\Api\V1\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1/auth')->group(function (): void {
    Route::post('login', [AuthController::class, 'login']);
});

Route::prefix('v1')->middleware(['auth:sanctum'])->group(function (): void {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('docs', [ApiDocumentationController::class, 'index']);
    Route::get('api-tokens', [ApiTokenController::class, 'index'])->middleware('permission:api-tokens.view');
    Route::post('api-tokens', [ApiTokenController::class, 'store'])->middleware('permission:api-tokens.create');
    Route::delete('api-tokens/{id}', [ApiTokenController::class, 'destroy'])->middleware('permission:api-tokens.delete');
    Route::get('permissions', [PermissionController::class, 'index'])->middleware('permission:roles.view');
    Route::get('roles', [RoleController::class, 'index'])->middleware('permission:roles.view');
    Route::post('roles', [RoleController::class, 'store'])->middleware('permission:roles.create');
    Route::get('roles/{id}', [RoleController::class, 'show'])->middleware('permission:roles.view');
    Route::put('roles/{id}', [RoleController::class, 'update'])->middleware('permission:roles.update');
    Route::delete('roles/{id}', [RoleController::class, 'destroy'])->middleware('permission:roles.delete');
    Route::get('audit-logs', [AuditLogController::class, 'index']);
    Route::get('branding', [BrandingController::class, 'show'])->middleware('permission:branding.view');
    Route::put('branding', [BrandingController::class, 'update'])->middleware('permission:branding.update');
    Route::get('email', [EmailController::class, 'show'])->middleware('permission:email.view');
    Route::put('email', [EmailController::class, 'update'])->middleware('permission:email.update');
    Route::post('email/test', [EmailController::class, 'test'])->middleware('permission:email.test');
    Route::get('notifications', [NotificationController::class, 'show'])->middleware('permission:notifications.view');
    Route::put('notifications', [NotificationController::class, 'update'])->middleware('permission:notifications.update');
    Route::post('notifications/test', [NotificationController::class, 'test'])->middleware('permission:notifications.test');
    Route::get('paymongo', [PaymongoController::class, 'show'])->middleware('permission:paymongo.view');
    Route::put('paymongo', [PaymongoController::class, 'update'])->middleware('permission:paymongo.update');
    Route::post('paymongo/test', [PaymongoController::class, 'test'])->middleware('permission:paymongo.test');
    Route::post('paymongo/test-payment', [PaymongoController::class, 'testPayment'])->middleware('permission:paymongo.test');
    Route::get('gcash', [GcashController::class, 'show'])->middleware('permission:gcash.view');
    Route::put('gcash', [GcashController::class, 'update'])->middleware('permission:gcash.update');
    Route::get('gcash/payments', [GcashController::class, 'payments'])->middleware('permission:gcash.view');
    Route::get('gcash/invoices', [GcashController::class, 'invoices'])->middleware('permission:gcash.view');
    Route::get('gcash/statements', [GcashController::class, 'statements'])->middleware('permission:gcash.view');
    Route::post('gcash/payments', [GcashController::class, 'store'])->middleware('permission:gcash.create');
    Route::post('gcash/payments/{id}/review', [GcashController::class, 'review'])->middleware('permission:gcash.review');
    Route::get('gcash/payments/{id}/receipt', [GcashController::class, 'receipt'])->middleware('permission:gcash.view');
    Route::get('users', [UserController::class, 'index'])->middleware('permission:users.view');
    Route::post('users', [UserController::class, 'store'])->middleware('permission:users.create');
    Route::get('users/{publicId}', [UserController::class, 'show'])->middleware('permission:users.view');
    Route::put('users/{publicId}', [UserController::class, 'update'])->middleware('permission:users.update');
    Route::delete('users/{publicId}', [UserController::class, 'destroy'])->middleware('permission:users.delete');
    Route::get('customers', [CustomerController::class, 'index'])->middleware('api.ability:customers.view');
    Route::post('customers', [CustomerController::class, 'store'])->middleware('api.ability:customers.create');
    Route::get('customers/{publicId}', [CustomerController::class, 'show'])->middleware('api.ability:customers.view');
    Route::put('customers/{publicId}', [CustomerController::class, 'update'])->middleware('api.ability:customers.update');
    Route::delete('customers/{publicId}', [CustomerController::class, 'destroy'])->middleware('api.ability:customers.delete');
    Route::get('billing-accounts', [BillingController::class, 'accounts'])->middleware('api.ability:billing-accounts.view');
    Route::post('billing-accounts', [BillingController::class, 'storeAccount'])->middleware('api.ability:billing-accounts.create');
    Route::delete('billing-accounts/{publicId}', [BillingController::class, 'destroyAccount'])->middleware('api.ability:billing-accounts.delete');
    Route::get('plans', [BillingController::class, 'plans'])->middleware('api.ability:plans.view');
    Route::post('plans', [BillingController::class, 'storePlan'])->middleware('api.ability:plans.create');
    Route::put('plans/{id}', [BillingController::class, 'updatePlan'])->middleware('api.ability:plans.update');
    Route::delete('plans/{id}', [BillingController::class, 'destroyPlan'])->middleware('api.ability:plans.delete');
    Route::get('subscriber-services', [BillingController::class, 'services'])->middleware('api.ability:subscriber-services.view');
    Route::post('subscriber-services', [BillingController::class, 'storeService'])->middleware('api.ability:subscriber-services.create');
    Route::get('subscriptions', [BillingController::class, 'subscriptions'])->middleware('api.ability:subscriptions.view');
    Route::post('subscriptions', [BillingController::class, 'storeSubscription'])->middleware('api.ability:subscriptions.create');
    Route::put('subscriptions/{id}', [BillingController::class, 'updateSubscription'])->middleware('api.ability:subscriptions.update');
    Route::delete('subscriptions/{id}', [BillingController::class, 'destroySubscription'])->middleware('api.ability:subscriptions.delete');
    Route::get('billing-settings', [BillingController::class, 'billingSettings'])->middleware('api.ability:billing.view');
    Route::put('billing-settings', [BillingController::class, 'updateBillingSettings'])->middleware('api.ability:billing.update');
    Route::get('billing-statements', [BillingController::class, 'statements'])->middleware('api.ability:billing-statements.view');
    Route::post('billing-statements', [BillingController::class, 'generateStatement'])->middleware('api.ability:billing-statements.create');
    Route::delete('billing-statements/{id}', [BillingController::class, 'destroyStatement'])->middleware('api.ability:billing-statements.delete');
    Route::get('routers', [RouterController::class, 'index'])->middleware('permission:routers.view');
    Route::post('routers', [RouterController::class, 'store'])->middleware('permission:routers.create');
    Route::get('routers/{publicId}', [RouterController::class, 'show'])->middleware('permission:routers.view');
    Route::get('routers/{publicId}/credentials', [RouterController::class, 'credentials'])->middleware('router.credential.permission:view');
    Route::put('routers/{publicId}/credentials', [RouterController::class, 'updateCredentials'])->middleware('router.credential.permission:manage');
    Route::put('routers/{publicId}', [RouterController::class, 'update'])->middleware('permission:routers.update');
    Route::delete('routers/{publicId}', [RouterController::class, 'destroy'])->middleware('permission:routers.delete');
    Route::post('routers/{publicId}/connection-test', [RouterController::class, 'connectionTest'])->middleware('permission:routers.test');
    Route::get('routers/{publicId}/system-info', [RouterController::class, 'systemInfo'])->middleware('permission:routers.test');
    Route::get('invoices', [BillingController::class, 'invoices'])->middleware('api.ability:invoices.view');
    Route::post('invoices', [BillingController::class, 'storeInvoice'])->middleware('api.ability:invoices.create');
    Route::get('payments', [BillingController::class, 'payments'])->middleware('api.ability:payments.view');
    Route::post('payments', [BillingController::class, 'storePayment'])->middleware('api.ability:payments.create');
});

Route::prefix('v1')->middleware(['auth:sanctum'])->group(function (): void {
    Route::post('routers/{publicId}/operations', [RouterController::class, 'storeOperation'])->middleware('router.operation.permission');
    Route::get('routers/{publicId}/operations', [RouterController::class, 'operations'])->middleware('router.operation.permission:history');
    Route::get('routers/{publicId}/operations/{operationPublicId}', [RouterController::class, 'showOperation'])->middleware('router.operation.permission:history');
});
