import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { XIcon } from '@phosphor-icons/react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import type { Role, User, UserRequest } from '@/lib/usersRoles'

export function UserForm({ open, mode, user, roles, error, loading, onClose, onSubmit }: { open: boolean; mode: 'create' | 'edit'; user?: User; roles: Role[]; error?: string; loading?: boolean; onClose: () => void; onSubmit: (payload: UserRequest) => Promise<void> }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [status, setStatus] = useState<'active' | 'inactive'>('active'); const [roleIds, setRoleIds] = useState<number[]>([])
  useEffect(() => { setName(user?.name || ''); setEmail(user?.email || ''); setPassword(''); setStatus(user?.membership_status === 'inactive' ? 'inactive' : 'active'); setRoleIds(user?.roles.map(role => role.id) || []) }, [user, mode, open])
  if (!open) return null
  const submit = async (event: FormEvent) => { event.preventDefault(); await onSubmit({ name, email, ...(password ? { password } : {}), status, role_ids: roleIds }) }
  const toggleRole = (id: number) => setRoleIds(ids => ids.includes(id) ? ids.filter(current => current !== id) : [...ids, id])
  return <div className="billing-modal-backdrop fixed inset-0 z-50 grid place-items-center overflow-y-auto p-4" role="dialog" aria-modal="true" aria-labelledby="user-form-title"><Card className="billing-modal-card relative w-full max-w-xl shadow-2xl"><CardHeader className="border-b pr-14"><p className="billing-modal-eyebrow">{mode === 'create' ? 'Create account' : 'Update account'}</p><CardTitle id="user-form-title">{mode === 'create' ? 'New user' : 'Edit user'}</CardTitle><CardDescription>Manage organization access and assigned roles.</CardDescription><Button type="button" variant="ghost" size="icon-sm" className="absolute right-4 top-4" onClick={onClose} aria-label="Close user form"><XIcon /></Button></CardHeader><CardContent className="pt-5"><form onSubmit={submit}><FieldGroup className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="user-name">Name</FieldLabel><Input id="user-name" value={name} onChange={event => setName(event.target.value)} required /></Field><Field><FieldLabel htmlFor="user-email">Email</FieldLabel><Input id="user-email" type="email" value={email} onChange={event => setEmail(event.target.value)} required /></Field><Field><FieldLabel htmlFor="user-password">Password</FieldLabel><Input id="user-password" type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} required={mode === 'create'} placeholder={mode === 'edit' ? 'Leave blank to keep current password' : 'Set a password'} /></Field><Field><FieldLabel htmlFor="user-status">Status</FieldLabel><select id="user-status" className="h-8 border border-input bg-transparent px-2.5 text-xs" value={status} onChange={event => setStatus(event.target.value as 'active' | 'inactive')}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field><Field className="sm:col-span-2"><FieldLabel>Roles</FieldLabel><div className="grid gap-2 rounded-sm border border-border/70 p-3 sm:grid-cols-2">{roles.map(role => <label className="flex items-center gap-2 text-xs" key={role.id}><input type="checkbox" checked={roleIds.includes(role.id)} onChange={() => toggleRole(role.id)} />{role.name}</label>)}</div></Field></FieldGroup>{error && <p className="mt-4 text-xs text-destructive">{error}</p>}<div className="mt-6 flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={loading}>{loading ? 'Saving…' : mode === 'create' ? 'Create user' : 'Save changes'}</Button></div></form></CardContent></Card></div>
}
