<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Models\Bng;
use App\Models\BngCgnatPolicy;
use App\Models\BngForwardingRule;
use App\Models\BngRadiusServer;
use App\Models\BngSpeedBoost;
use App\Models\BngVlanSync;
use App\Models\Olt;
use App\Models\Plan;
use App\Services\BngSessionService;
use App\Services\BngSpeedBoostService;
use App\Services\BngVlanSyncService;
use App\Services\RadiusSubscriberSyncService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class BngController extends Controller {
 public function index(): JsonResponse { return response()->json(['data'=>Bng::query()->latest()->get()]); }
 public function show(string $publicId): JsonResponse { return response()->json(['data'=>Bng::where('public_id',$publicId)->firstOrFail()]); }
 public function updateInterfaces(Request $request, string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['parent_interface'=>'required|string|max:255','egress_interface'=>'required|string|max:255']); $b->update($v); return response()->json(['data'=>$b->fresh()]); }
 public function vlanSyncs(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->vlanSyncs()->with('olt:id,public_id,name,vendor')->latest()->get()->map(fn (BngVlanSync $sync) => $this->serializeVlanSync($sync))]); }
 public function storeVlanSync(Request $request,string $publicId,BngVlanSyncService $vlanSync): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['olt_id'=>'required|string','vlan_mode'=>['required',Rule::in(['normal','qinq'])],'enabled'=>'required|boolean']); $olt=Olt::where('public_id',$v['olt_id'])->first(); if (!$olt) throw ValidationException::withMessages(['olt_id'=>'Select an existing OLT.']); if ($b->vlanSyncs()->where('olt_id',$olt->id)->where('vlan_mode',$v['vlan_mode'])->exists()) throw ValidationException::withMessages(['vlan_mode'=>'This OLT and VLAN type already have a sync rule for this BNG.']); $sync=$b->vlanSyncs()->create(['olt_id'=>$olt->id,'vlan_mode'=>$v['vlan_mode'],'enabled'=>$v['enabled']]); $operation=$vlanSync->reconcileRule($sync->load('olt')); return response()->json(['data'=>$this->serializeVlanSync($sync->load('olt:id,public_id,name,vendor')),'operation'=>$operation],201); }
 public function updateVlanSync(Request $request,string $publicId,string $syncId,BngVlanSyncService $vlanSync): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $sync=$b->vlanSyncs()->where('public_id',$syncId)->firstOrFail(); $v=$request->validate(['enabled'=>'required|boolean']); $sync->update(['enabled'=>$v['enabled']]); $operation=$sync->enabled ? $vlanSync->reconcileRule($sync->fresh('olt')) : ['warnings'=>[]]; return response()->json(['data'=>$this->serializeVlanSync($sync->fresh('olt:id,public_id,name,vendor')),'operation'=>$operation]); }
 public function destroyVlanSync(string $publicId,string $syncId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $sync=$b->vlanSyncs()->where('public_id',$syncId)->firstOrFail(); $result=app(\App\Services\BngVlanSyncService::class)->removeRule($sync); $sync->delete(); return response()->json(['message'=>'VLAN sync removed.','cleanup'=>$result]); }
 public function store(Request $request): JsonResponse { $v=$request->validate(['name'=>'required|string','vendor'=>'required|in:linux,mikrotik','model'=>'nullable|string','management_endpoint'=>'required|string','preferred_transport'=>'required|in:ssh','username'=>'required|string','password'=>'required|string','status'=>'required|string','notes'=>'nullable|string']); $v['ssh_username']=$v['username']; $v['ssh_password']=$v['password']; unset($v['username'],$v['password']); return response()->json(['data'=>Bng::create($v)->fresh()],201); }
 public function update(Request $request, string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string','vendor'=>'required|in:linux,mikrotik','model'=>'nullable|string','management_endpoint'=>'required|string','preferred_transport'=>'required|in:ssh','username'=>'nullable|string','password'=>'nullable|string','status'=>'required|string','notes'=>'nullable|string']); if(array_key_exists('username',$v)&&filled($v['username'])) $v['ssh_username']=$v['username']; if(array_key_exists('password',$v)&&filled($v['password'])) $v['ssh_password']=$v['password']; unset($v['username'],$v['password']); $b->update($v); return response()->json(['data'=>$b->fresh()]); }
 public function destroy(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>false]); $b->delete(); return response()->json(['message'=>'BNG archived.']); }
 public function accelPppConfig(string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->readAccelPppConfig($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function previewAccelPppConfig(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->previewAccelPppConfig($b,$this->accelPppValues($request,true))]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function saveAccelPppConfig(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->saveAccelPppConfig($b,$this->accelPppValues($request,true))]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 private function accelPppValues(Request $request, bool $preview = false): array { $rules=['bras_name'=>'string','gateway_address'=>'ip','pool_name'=>'string','pool_start'=>'ip','pool_end'=>'ip','nas_ip'=>'ip','nas_identifier'=>'string','radius_gateway_address'=>'ip','radius_server'=>'string','radius_secret'=>'string','auth_port'=>'integer|between:1,65535','acct_port'=>'integer|between:1,65535','dae_server'=>'ip','dae_port'=>'integer|between:1,65535','dae_secret'=>'string','primary_dns'=>'ip','secondary_dns'=>'ip']; if(!$preview) $rules=array_map(fn($rule)=>'required|'.$rule,$rules); else { $rules=array_map(fn($rule)=>'nullable|'.$rule,$rules); $request->merge(collect($request->all())->reject(fn($value)=>is_string($value)&&trim($value)==='')->all()); } return $request->validate($rules); }
 public function cgnatPolicies(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->cgnatPolicies()->latest()->get()]); }
 public function storeCgnatPolicy(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate($this->cgnatRules()); $v['bng_id']=$b->id; return response()->json(['data'=>BngCgnatPolicy::create($v)],201); }
 public function destroyCgnatPolicy(string $publicId,string $policyId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->cgnatPolicies()->where('public_id',$policyId)->firstOrFail()->delete(); return response()->json(['message'=>'CGNAT policy removed.']); }
 public function forwardingRules(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->forwardingRules()->latest()->get()]); }
 public function storeForwardingRule(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','customer_interface'=>'required|string|max:64','internet_interface'=>'required|string|max:64','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); $v['bng_id']=$b->id; return response()->json(['data'=>BngForwardingRule::create($v)],201); }
 public function destroyForwardingRule(string $publicId,string $ruleId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->forwardingRules()->where('public_id',$ruleId)->firstOrFail()->delete(); return response()->json(['message'=>'Forwarding rule removed.']); }
 public function radiusServers(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->radiusServers()->latest()->get()->makeVisible('secret')]); }
 public function storeRadiusServer(Request $request,string $publicId,RadiusSubscriberSyncService $sync): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','server_address'=>'required|ip','secret'=>'required|string|max:255','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'required|string|max:255','sync_subscribers'=>'sometimes|boolean','auth_port'=>'required|integer|between:1,65535','accounting_port'=>'required|integer|between:1,65535','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); $v['bng_id']=$b->id; $server=BngRadiusServer::create($v); $syncResult=null; if($server->sync_subscribers) $syncResult=$this->backfillRadiusSubscribers($sync,$server); return response()->json(['data'=>$server->fresh(),'sync'=>$syncResult],201); }
 public function updateRadiusServer(Request $request,string $publicId,string $serverId,RadiusSubscriberSyncService $sync): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $server=$b->radiusServers()->where('public_id',$serverId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','server_address'=>'required|ip','secret'=>'nullable|string|max:255','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'nullable|string|max:255','sync_subscribers'=>'sometimes|boolean','auth_port'=>'required|integer|between:1,65535','accounting_port'=>'required|integer|between:1,65535','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); foreach(['secret','database_password'] as $key) if(array_key_exists($key,$v)&&blank($v[$key])) unset($v[$key]); $server->update($v); $syncResult=null; if($server->sync_subscribers) $syncResult=$this->backfillRadiusSubscribers($sync,$server); return response()->json(['data'=>$server->fresh(),'sync'=>$syncResult]); }
 public function testRadiusDatabase(Request $request,string $publicId): JsonResponse { Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['server_address'=>'required|ip','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'required|string|max:255']); try { $dsn="mysql:host={$v['server_address']};port=3306;dbname=".rawurlencode($v['database_name']); $pdo=new \PDO($dsn,$v['database_username'],$v['database_password'],[\PDO::ATTR_TIMEOUT=>5,\PDO::ATTR_ERRMODE=>\PDO::ERRMODE_EXCEPTION]); $pdo=null; return response()->json(['message'=>'Database connection successful.']); } catch (\Throwable $e) { return response()->json(['message'=>'Database connection failed. Check the server address, database name, username, and password.'],422); } }
 public function destroyRadiusServer(string $publicId,string $serverId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->radiusServers()->where('public_id',$serverId)->firstOrFail()->delete(); return response()->json(['message'=>'RADIUS server removed.']); }
 public function speedBoosts(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->speedBoosts()->with(['radiusServer','plan'])->latest()->get()]); }
 public function previewSpeedBoost(Request $request,string $publicId,BngSpeedBoostService $speedBoosts): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$this->speedBoostValues($request,true); $plan=isset($v['plan_id']) ? Plan::find($v['plan_id']) : null; $server=isset($v['radius_server_id']) ? $b->radiusServers()->where('public_id',$v['radius_server_id'])->first() : null; $rate=null; $missing=[]; foreach(['radius_server_id','plan_id','download_mbps','upload_mbps'] as $key) if (!array_key_exists($key,$v) || blank($v[$key])) $missing[]=$key; if (isset($v['download_mbps'],$v['upload_mbps'])) $rate=BngSpeedBoostService::filterIdValue($v['download_mbps'],$v['upload_mbps']); $usernames=$plan ? $speedBoosts->usernamesForPlan($plan) : []; $sql=[]; if ($rate) foreach ($usernames as $username) { $safe=str_replace("'", "''", $username); $sql[]="DELETE FROM radreply WHERE username = '{$safe}' AND attribute = 'Filter-Id';"; $sql[]="INSERT INTO radreply (username, attribute, op, value) VALUES ('{$safe}', 'Filter-Id', ':=', '{$rate}');"; } return response()->json(['data'=>['rate_value'=>$rate,'usernames'=>$usernames,'user_count'=>count($usernames),'missing'=>$missing,'sql'=>$sql,'plan'=>$plan?->only(['id','public_id','name']),'radius_server'=>$server?->only(['public_id','name','server_address']),'radius_server_id'=>$v['radius_server_id'] ?? null]]); }
 public function storeSpeedBoost(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); [$v,$server,$plan]=$this->speedBoostContext($request,$b); $this->ensureSpeedBoostUnique($b,$server,$plan); $boost=BngSpeedBoost::create(['bng_id'=>$b->id,'bng_radius_server_id'=>$server->id,'plan_id'=>$plan->id,'download_kbps'=>BngSpeedBoostService::mbpsToKbps($v['download_mbps']),'upload_kbps'=>BngSpeedBoostService::mbpsToKbps($v['upload_mbps']),'status'=>'draft','synced_user_count'=>0]); return response()->json(['data'=>$boost->load(['radiusServer','plan'])],201); }
 public function updateSpeedBoost(Request $request,string $publicId,string $boostId,BngSpeedBoostService $speedBoosts): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $boost=$b->speedBoosts()->with(['radiusServer','syncs'])->where('public_id',$boostId)->firstOrFail(); [$v,$server,$plan]=$this->speedBoostContext($request,$b); $this->ensureSpeedBoostUnique($b,$server,$plan,$boost->id); if ($boost->syncs->isNotEmpty() && ($boost->bng_radius_server_id !== $server->id || $boost->plan_id !== $plan->id)) $speedBoosts->removeManagedRows($boost->radiusServer,$boost->syncs->map(fn ($row)=>['username'=>$row->username,'value'=>$row->rate_value])->all()); if ($boost->syncs->isNotEmpty() && ($boost->bng_radius_server_id !== $server->id || $boost->plan_id !== $plan->id)) $boost->syncs()->delete(); $boost->update(['bng_radius_server_id'=>$server->id,'plan_id'=>$plan->id,'download_kbps'=>BngSpeedBoostService::mbpsToKbps($v['download_mbps']),'upload_kbps'=>BngSpeedBoostService::mbpsToKbps($v['upload_mbps']),'status'=>'draft','last_error'=>null]); return response()->json(['data'=>$boost->fresh()->load(['radiusServer','plan'])]); }
 public function applySpeedBoost(string $publicId,string $boostId,BngSpeedBoostService $speedBoosts): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $boost=$b->speedBoosts()->with(['radiusServer','plan','syncs'])->where('public_id',$boostId)->firstOrFail(); $rate=BngSpeedBoostService::filterIdValue($boost->download_kbps/1000,$boost->upload_kbps/1000); $usernames=$speedBoosts->usernamesForPlan($boost->plan); try { $count=$speedBoosts->replaceManagedRows($boost->radiusServer,$boost->syncs->map(fn ($row)=>['username'=>$row->username,'value'=>$row->rate_value])->all(),$usernames,$rate); \DB::transaction(function () use ($boost,$usernames,$rate,$count): void { $boost->syncs()->delete(); $now=now(); foreach ($usernames as $username) $boost->syncs()->create(['username'=>$username,'rate_value'=>$rate,'applied_at'=>$now]); $boost->update(['status'=>'applied','last_error'=>null,'last_applied_at'=>$now,'synced_user_count'=>$count]); }); return response()->json(['data'=>$boost->fresh()->load(['radiusServer','plan'])]); } catch (\Throwable $exception) { $boost->update(['status'=>'error','last_error'=>$exception->getMessage()]); return response()->json(['message'=>$exception->getMessage(),'data'=>$boost->fresh()],422); } }
 public function destroySpeedBoost(string $publicId,string $boostId,BngSpeedBoostService $speedBoosts): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $boost=$b->speedBoosts()->with(['radiusServer','syncs'])->where('public_id',$boostId)->firstOrFail(); try { $speedBoosts->removeManagedRows($boost->radiusServer,$boost->syncs->map(fn ($row)=>['username'=>$row->username,'value'=>$row->rate_value])->all()); $boost->delete(); return response()->json(['message'=>'Speed Boost removed.']); } catch (\Throwable $exception) { return response()->json(['message'=>$exception->getMessage()],422); } }
 public function previewIptables(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->previewIptables($b,$request->all())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function saveIptables(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->saveIptables($b,$request->all())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 private function cgnatRules(): array { $cidr='/^([0-9]{1,3}\.){3}[0-9]{1,3}\/([0-9]|[1-2][0-9]|3[0-2])$/'; return ['name'=>'required|string|max:120','subscriber_network'=>['required','string','max:64',"regex:$cidr"],'public_ip_mode'=>['required',Rule::in(['single','range','masquerade'])],'public_ip_start'=>'required_unless:public_ip_mode,masquerade|nullable|ip','public_ip_end'=>'required_if:public_ip_mode,range|nullable|ip','local_bypass_network'=>['nullable','string','max:64',"regex:$cidr"],'status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']; }
 private function speedBoostValues(Request $request,bool $preview=false): array { $rules=['radius_server_id'=>[$preview?'nullable':'required','string'],'plan_id'=>[$preview?'nullable':'required','integer','exists:plans,id'],'download_mbps'=>[$preview?'nullable':'required','numeric','gt:0','max:4294967.295'],'upload_mbps'=>[$preview?'nullable':'required','numeric','gt:0','max:4294967.295']]; return $request->validate($rules); }
 private function speedBoostContext(Request $request,Bng $b): array { $v=$this->speedBoostValues($request); $server=$b->radiusServers()->where('public_id',$v['radius_server_id'])->firstOrFail(); $plan=Plan::findOrFail($v['plan_id']); return [$v,$server,$plan]; }
 private function ensureSpeedBoostUnique(Bng $b,BngRadiusServer $server,Plan $plan,?int $ignore=null): void { $exists=$b->speedBoosts()->where('bng_radius_server_id',$server->id)->where('plan_id',$plan->id)->when($ignore,fn ($query)=>$query->where('id','!=',$ignore))->exists(); if ($exists) throw ValidationException::withMessages(['plan_id'=>'A Speed Boost already exists for this Plan and RADIUS server.']); }
 private function backfillRadiusSubscribers(RadiusSubscriberSyncService $sync,BngRadiusServer $server): array { try { return $sync->syncServer($server); } catch (\Throwable $exception) { throw ValidationException::withMessages(['sync_subscribers'=>$exception->getMessage()]); } }
 public function connect(string $publicId,BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>true]); return response()->json(['data'=>$sessions->start($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function disconnect(string $publicId,BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>false]); return response()->json(['data'=>$sessions->stop($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function sessionStatus(string $publicId,BngSessionService $sessions): JsonResponse { try { return response()->json(['data'=>$sessions->status(Bng::where('public_id',$publicId)->firstOrFail())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 private function serializeVlanSync(BngVlanSync $sync): array { return ['public_id'=>$sync->public_id,'vlan_mode'=>$sync->vlan_mode,'enabled'=>(bool) $sync->enabled,'olt'=>$sync->olt?->only(['public_id','name','vendor']),'interfaces'=>$sync->bng?->vlanInterfaces()->where('olt_id',$sync->olt_id)->latest()->get(['interface_name','vlan_mode','outer_vlan','inner_vlan','status','last_error']) ?? []]; }
}
