<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;
use App\Models\Bng;
use App\Models\BngCgnatPolicy;
use App\Models\BngForwardingRule;
use App\Models\BngRadiusServer;
use App\Services\BngSessionService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use RuntimeException;
class BngController extends Controller {
 public function index(): JsonResponse { return response()->json(['data'=>Bng::query()->latest()->get()]); }
 public function show(string $publicId): JsonResponse { return response()->json(['data'=>Bng::where('public_id',$publicId)->firstOrFail()]); }
 public function updateInterfaces(Request $request, string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['parent_interface'=>'required|string|max:255','egress_interface'=>'required|string|max:255']); $b->update($v); return response()->json(['data'=>$b->fresh()]); }
 public function store(Request $request): JsonResponse { $v=$request->validate(['name'=>'required|string','vendor'=>'required|in:linux,mikrotik','model'=>'nullable|string','management_endpoint'=>'required|string','preferred_transport'=>'required|in:ssh','username'=>'required|string','password'=>'required|string','status'=>'required|string','notes'=>'nullable|string']); $v['ssh_username']=$v['username']; $v['ssh_password']=$v['password']; unset($v['username'],$v['password']); return response()->json(['data'=>Bng::create($v)->fresh()],201); }
 public function update(Request $request, string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string','vendor'=>'required|in:linux,mikrotik','model'=>'nullable|string','management_endpoint'=>'required|string','preferred_transport'=>'required|in:ssh','username'=>'nullable|string','password'=>'nullable|string','status'=>'required|string','notes'=>'nullable|string']); if(array_key_exists('username',$v)&&filled($v['username'])) $v['ssh_username']=$v['username']; if(array_key_exists('password',$v)&&filled($v['password'])) $v['ssh_password']=$v['password']; unset($v['username'],$v['password']); $b->update($v); return response()->json(['data'=>$b->fresh()]); }
 public function destroy(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>false]); $b->delete(); return response()->json(['message'=>'BNG archived.']); }
 public function accelPppConfig(string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->readAccelPppConfig($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function previewAccelPppConfig(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->previewAccelPppConfig($b,$this->accelPppValues($request,true))]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function saveAccelPppConfig(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->saveAccelPppConfig($b,$this->accelPppValues($request,true))]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 private function accelPppValues(Request $request, bool $preview = false): array { $rules=['bras_name'=>'string','gateway_address'=>'ip','pool_name'=>'string','pool_start'=>'ip','pool_end'=>'ip','nas_ip'=>'ip','nas_identifier'=>'string','radius_gateway_address'=>'ip','radius_server'=>'string','radius_secret'=>'string','auth_port'=>'integer|between:1,65535','acct_port'=>'integer|between:1,65535','dae_server'=>'ip','dae_port'=>'integer|between:1,65535','dae_secret'=>'string','primary_dns'=>'ip','secondary_dns'=>'ip']; if(!$preview) $rules=array_map(fn($rule)=>'required|'.$rule,$rules); else { $rules=array_map(fn($rule)=>'nullable|'.$rule,$rules); $request->merge(collect($request->all())->reject(fn($value)=>is_string($value)&&trim($value)==='')->all()); } return $request->validate($rules); }
 public function cgnatPolicies(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->cgnatPolicies()->latest()->get()]); }
 public function storeCgnatPolicy(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate($this->cgnatRules()); $v['bng_id']=$b->id; return response()->json(['data'=>BngCgnatPolicy::create($v)],201); }
 public function destroyCgnatPolicy(string $publicId,string $policyId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->cgnatPolicies()->where('public_id',$policyId)->firstOrFail()->delete(); return response()->json(['message'=>'CGNAT policy removed.']); }
 public function forwardingRules(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->forwardingRules()->latest()->get()]); }
 public function storeForwardingRule(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','customer_interface'=>'required|string|max:64','internet_interface'=>'required|string|max:64','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); $v['bng_id']=$b->id; return response()->json(['data'=>BngForwardingRule::create($v)],201); }
 public function destroyForwardingRule(string $publicId,string $ruleId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->forwardingRules()->where('public_id',$ruleId)->firstOrFail()->delete(); return response()->json(['message'=>'Forwarding rule removed.']); }
 public function radiusServers(string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$b->radiusServers()->latest()->get()->makeVisible('secret')]); }
 public function storeRadiusServer(Request $request,string $publicId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','server_address'=>'required|ip','secret'=>'required|string|max:255','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'required|string|max:255','auth_port'=>'required|integer|between:1,65535','accounting_port'=>'required|integer|between:1,65535','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); $v['bng_id']=$b->id; return response()->json(['data'=>BngRadiusServer::create($v)],201); }
 public function updateRadiusServer(Request $request,string $publicId,string $serverId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $server=$b->radiusServers()->where('public_id',$serverId)->firstOrFail(); $v=$request->validate(['name'=>'required|string|max:120','server_address'=>'required|ip','secret'=>'nullable|string|max:255','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'nullable|string|max:255','auth_port'=>'required|integer|between:1,65535','accounting_port'=>'required|integer|between:1,65535','status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']); foreach(['secret','database_password'] as $key) if(array_key_exists($key,$v)&&blank($v[$key])) unset($v[$key]); $server->update($v); return response()->json(['data'=>$server->fresh()]); }
 public function testRadiusDatabase(Request $request,string $publicId): JsonResponse { Bng::where('public_id',$publicId)->firstOrFail(); $v=$request->validate(['server_address'=>'required|ip','database_name'=>'required|string|max:120','database_username'=>'required|string|max:120','database_password'=>'required|string|max:255']); try { $dsn="mysql:host={$v['server_address']};port=3306;dbname=".rawurlencode($v['database_name']); $pdo=new \PDO($dsn,$v['database_username'],$v['database_password'],[\PDO::ATTR_TIMEOUT=>5,\PDO::ATTR_ERRMODE=>\PDO::ERRMODE_EXCEPTION]); $pdo=null; return response()->json(['message'=>'Database connection successful.']); } catch (\Throwable $e) { return response()->json(['message'=>'Database connection failed. Check the server address, database name, username, and password.'],422); } }
 public function destroyRadiusServer(string $publicId,string $serverId): JsonResponse { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->radiusServers()->where('public_id',$serverId)->firstOrFail()->delete(); return response()->json(['message'=>'RADIUS server removed.']); }
 public function previewIptables(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->previewIptables($b,$request->all())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function saveIptables(Request $request, string $publicId, BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); return response()->json(['data'=>$sessions->saveIptables($b,$request->all())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 private function cgnatRules(): array { $cidr='/^([0-9]{1,3}\.){3}[0-9]{1,3}\/([0-9]|[1-2][0-9]|3[0-2])$/'; return ['name'=>'required|string|max:120','subscriber_network'=>['required','string','max:64',"regex:$cidr"],'public_ip_mode'=>['required',Rule::in(['single','range','masquerade'])],'public_ip_start'=>'required_unless:public_ip_mode,masquerade|nullable|ip','public_ip_end'=>'required_if:public_ip_mode,range|nullable|ip','local_bypass_network'=>['nullable','string','max:64',"regex:$cidr"],'status'=>['nullable',Rule::in(['draft','ready'])],'notes'=>'nullable|string']; }
 public function connect(string $publicId,BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>true]); return response()->json(['data'=>$sessions->start($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function disconnect(string $publicId,BngSessionService $sessions): JsonResponse { try { $b=Bng::where('public_id',$publicId)->firstOrFail(); $b->update(['session_requested'=>false]); return response()->json(['data'=>$sessions->stop($b)]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
 public function sessionStatus(string $publicId,BngSessionService $sessions): JsonResponse { try { return response()->json(['data'=>$sessions->status(Bng::where('public_id',$publicId)->firstOrFail())]); } catch(RuntimeException $e) { return response()->json(['message'=>$e->getMessage()],422); } }
}
