import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { apiRequest } from './lib/api'
import { formatDate, formatMoney } from './lib/formatters'

type View = 'overview' | 'customers' | 'accounts' | 'plans' | 'services' | 'subscriptions' | 'invoices' | 'payments'
type Session = { token: string; user: { name: string; email: string }; organization: { name: string; default_currency: string } }
type Row = Record<string, any>

const nav: { key: View; label: string; section: string }[] = [
  { key: 'overview', label: 'Overview', section: 'Workspace' }, { key: 'customers', label: 'Customers', section: 'Workspace' },
  { key: 'accounts', label: 'Billing accounts', section: 'Billing' }, { key: 'plans', label: 'Plans', section: 'Billing' },
  { key: 'services', label: 'Subscriber services', section: 'Billing' }, { key: 'subscriptions', label: 'Subscriptions', section: 'Billing' },
  { key: 'invoices', label: 'Invoices', section: 'Billing' }, { key: 'payments', label: 'Payments', section: 'Billing' },
]

function App() {
  const [session, setSession] = useState<Session | null>(() => JSON.parse(localStorage.getItem('isp-session') || 'null'))
  const [view, setView] = useState<View>('overview')
  const [error, setError] = useState('')
  const signIn = (next: Session) => { localStorage.setItem('isp-session', JSON.stringify(next)); setSession(next); setError('') }
  const signOut = async () => { if (session) await apiRequest('/auth/logout', { method: 'POST' }, session.token).catch(() => undefined); localStorage.removeItem('isp-session'); setSession(null) }
  if (!session) return <Login onSignedIn={signIn} error={error} setError={setError} />
  return <Shell session={session} view={view} setView={setView} signOut={signOut} />
}

function Login({ onSignedIn, error, setError }: { onSignedIn: (s: Session) => void; error: string; setError: (s: string) => void }) {
  const [email, setEmail] = useState('admin@example.com'); const [password, setPassword] = useState('password'); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await apiRequest<{ data: Session }>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); onSignedIn(response.data) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to sign in.') } finally { setLoading(false) } }
  return <main className="login-shell"><section className="login-panel"><div className="brand-mark">NB</div><p className="eyebrow">NORTHSTAR BILLING</p><h1>Operations console</h1><p className="muted">Secure billing operations for ISP teams.</p><form onSubmit={submit} className="stack"><label>Email<input value={email} onChange={e => setEmail(e.target.value)} type="email" required /></label><label>Password<input value={password} onChange={e => setPassword(e.target.value)} type="password" required /></label>{error && <div className="alert error">{error}</div>}<button className="button primary" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form><p className="fine-print">Use the operator account configured by your deployment administrator.</p></section></main>
}

function Shell({ session, view, setView, signOut }: { session: Session; view: View; setView: (v: View) => void; signOut: () => void }) {
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark small">NB</span><div><strong>Northstar</strong><span>Billing operations</span></div></div><div className="tenant"><span className="status-dot" />{session.organization.name}<small>Active organization</small></div><nav>{(['Workspace', 'Billing'] as const).map(section => <div className="nav-group" key={section}><span className="nav-label">{section}</span>{nav.filter(item => item.section === section).map(item => <button key={item.key} className={view === item.key ? 'nav-item active' : 'nav-item'} onClick={() => setView(item.key)}>{item.label}</button>)}</div>)}</nav><div className="sidebar-footer"><button className="nav-item" onClick={signOut}>Sign out</button><span className="muted tiny">v0.1 billing foundation</span></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">ISP BILLING / {view.toUpperCase()}</span><h2>{nav.find(item => item.key === view)?.label}</h2></div><div className="user-chip"><span className="avatar">{session.user.name.slice(0, 1).toUpperCase()}</span><span>{session.user.name}</span></div></header><div className="content">{view === 'overview' ? <Overview session={session} /> : view === 'customers' ? <Customers session={session} /> : <ResourcePage session={session} view={view} />}</div></main></div>
}

function Overview({ session }: { session: Session }) {
  const [stats, setStats] = useState({ customers: 0, invoices: 0, payments: 0, services: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all(['customers', 'invoices', 'payments', 'subscriber-services'].map(endpoint => apiRequest<any>(`/${endpoint}?per_page=1`, {}, session.token))).then(([customers, invoices, payments, services]) => setStats({ customers: customers.data.total, invoices: invoices.data.total, payments: payments.data.total, services: services.data.total })).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [session.token])
  const cards = [['Customers', stats.customers, 'Active customer records'], ['Subscriber services', stats.services, 'Provisioning-ready services'], ['Invoices', stats.invoices, 'Issued billing documents'], ['Payments', stats.payments, 'Recorded receipts']]
  return <><div className="page-intro"><div><p className="eyebrow">CONTROL ROOM</p><h3>Billing overview</h3><p className="muted">A live view of the organization’s billing workload.</p></div><span className="sync-note">{loading ? 'Loading live data…' : 'Live API data'}</span></div>{error && <div className="alert error">{error}</div>}<div className="metric-grid">{cards.map(([label, value, note]) => <div className="metric" key={label as string}><span>{label}</span><strong>{loading ? '—' : value}</strong><small>{note}</small></div>)}</div><section className="panel two-column"><div><div className="panel-heading"><div><p className="eyebrow">FIRST MILESTONE</p><h4>Billing workflow</h4></div><span className="tag neutral">Operational</span></div><ol className="workflow"><li><span>01</span><div><strong>Customer</strong><small>Establish the account holder and contact record.</small></div></li><li><span>02</span><div><strong>Service and plan</strong><small>Connect the service to a versioned commercial plan.</small></div></li><li><span>03</span><div><strong>Invoice</strong><small>Generate an immutable charge with line items.</small></div></li><li><span>04</span><div><strong>Payment</strong><small>Allocate receipts and preserve the balance ledger.</small></div></li></ol></div><div className="callout"><p className="eyebrow">DATA INTEGRITY</p><h4>Tenant-scoped by default</h4><p>Every billing query is resolved through the active organization context. Cross-tenant records are rejected before they reach the operator interface.</p></div></section></>
}

function Customers({ session }: { session: Session }) {
  const [rows, setRows] = useState<Row[]>([]); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('')
  const load = useCallback(() => apiRequest<any>(`/customers?search=${encodeURIComponent(search)}`, {}, session.token).then(r => { setRows(r.data.data); setTotal(r.data.total) }).catch(e => setError(e.message)), [search, session.token])
  useEffect(() => { load() }, [load])
  const create = async (payload: Record<string, string>) => { await apiRequest('/customers', { method: 'POST', body: JSON.stringify(payload) }, session.token); setShowForm(false); load() }
  return <><div className="page-intro"><div><p className="eyebrow">CUSTOMER DIRECTORY</p><h3>Customers</h3><p className="muted">{total} records in the current organization.</p></div><button className="button primary" onClick={() => setShowForm(true)}>New customer</button></div><div className="toolbar"><input className="search" placeholder="Search name, number, or email" value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} /><button className="button secondary" onClick={load}>Search</button></div>{error && <div className="alert error">{error}</div>}<section className="panel table-panel"><TableHead columns={['Customer', 'Contact', 'Status', 'Created']} />{rows.length ? rows.map(row => <div className="table-row" key={row.id}><div><strong>{row.legal_name}</strong><small>{row.customer_number}</small></div><span>{row.email || 'No email'}</span><span><span className="tag success">{row.status}</span></span><span>{formatDate(row.created_at)}</span></div>) : <EmptyState title="No customers found" body="Create the first customer record to begin the billing workflow." />}</section>{showForm && <CustomerForm onCancel={() => setShowForm(false)} onSubmit={create} />}</>
}

function CustomerForm({ onCancel, onSubmit }: { onCancel: () => void; onSubmit: (p: Record<string, string>) => Promise<void> }) { const [form, setForm] = useState({ customer_type: 'residential', legal_name: '', email: '', phone: '' }); const [error, setError] = useState(''); const update = (key: string, value: string) => setForm(current => ({ ...current, [key]: value })); const submit = async (e: FormEvent) => { e.preventDefault(); try { await onSubmit(form) } catch (error) { setError(error instanceof Error ? error.message : 'Unable to save customer.') } }; return <div className="modal-backdrop"><form className="modal panel" onSubmit={submit}><div className="panel-heading"><div><p className="eyebrow">CUSTOMER RECORD</p><h4>New customer</h4></div><button type="button" className="close" onClick={onCancel}>Close</button></div><div className="form-grid"><label>Customer type<select value={form.customer_type} onChange={e => update('customer_type', e.target.value)}><option value="residential">Residential</option><option value="business">Business</option></select></label><label>Legal name<input value={form.legal_name} onChange={e => update('legal_name', e.target.value)} required /></label><label>Email<input type="email" value={form.email} onChange={e => update('email', e.target.value)} /></label><label>Phone<input value={form.phone} onChange={e => update('phone', e.target.value)} /></label></div>{error && <div className="alert error">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel</button><button className="button primary">Create customer</button></div></form></div> }

function ResourcePage({ session, view }: { session: Session; view: Exclude<View, 'overview' | 'customers'> }) { const endpoint = view === 'accounts' ? 'billing-accounts' : view === 'services' ? 'subscriber-services' : view; const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); useEffect(() => { apiRequest<any>(`/${endpoint}`, {}, session.token).then(r => setRows(r.data.data)).catch(e => setError(e.message)) }, [endpoint, session.token]); const columns = view === 'accounts' ? ['Account', 'Customer', 'Currency', 'Status'] : view === 'plans' ? ['Plan', 'Code', 'Speed', 'Status'] : view === 'services' ? ['Service', 'Customer', 'Type', 'Status'] : view === 'subscriptions' ? ['Plan', 'Service', 'Price', 'Status'] : view === 'invoices' ? ['Invoice', 'Due date', 'Total', 'Status'] : ['Payment', 'Reference', 'Amount', 'Status']; return <><div className="page-intro"><div><p className="eyebrow">{view.replace('-', ' ').toUpperCase()}</p><h3>{nav.find(item => item.key === view)?.label}</h3><p className="muted">Live records from the billing API.</p></div>{view === 'invoices' && <span className="tag neutral">Financial records are immutable</span>}</div>{error && <div className="alert error">{error}</div>}<section className="panel table-panel"><TableHead columns={columns} />{rows.length ? rows.map(row => <ResourceRow key={row.id} row={row} view={view} />) : <EmptyState title="No records yet" body="Records will appear here once they are created through the billing workflow." />}</section></> }

function ResourceRow({ row, view }: { row: Row; view: string }) { if (view === 'accounts') return <div className="table-row"><div><strong>{row.account_number}</strong><small>{row.public_id}</small></div><span>{row.customer?.legal_name || '—'}</span><span>{row.currency}</span><span><span className="tag success">{row.status}</span></span></div>; if (view === 'plans') return <div className="table-row"><div><strong>{row.name}</strong><small>{row.code}</small></div><span>{row.service_type}</span><span>{row.versions?.[0] ? `${row.versions[0].download_kbps / 1000} / ${row.versions[0].upload_kbps / 1000} Mbps` : '—'}</span><span><span className="tag success">{row.status}</span></span></div>; if (view === 'services') return <div className="table-row"><div><strong>{row.service_number}</strong><small>{row.public_id}</small></div><span>{row.customer?.legal_name || '—'}</span><span>{row.service_type}</span><span><span className="tag warning">{row.status}</span></span></div>; if (view === 'subscriptions') return <div className="table-row"><div><strong>{row.plan_name_snapshot}</strong><small>Service #{row.subscriber_service_id}</small></div><span>{row.service?.service_number || '—'}</span><span>{formatMoney(row.price_snapshot_minor, row.currency_snapshot)}</span><span><span className="tag success">{row.status}</span></span></div>; if (view === 'invoices') return <div className="table-row"><div><strong>{row.invoice_number}</strong><small>{row.billing_account?.customer?.legal_name || '—'}</small></div><span>{formatDate(row.due_date)}</span><span>{formatMoney(row.total_minor, row.currency)}</span><span><span className={row.status === 'paid' ? 'tag success' : 'tag warning'}>{row.status}</span></span></div>; return <div className="table-row"><div><strong>{row.payment_number}</strong><small>{row.payment_method}</small></div><span>{row.reference || '—'}</span><span>{formatMoney(row.amount_minor, row.currency)}</span><span><span className="tag success">{row.status}</span></span></div> }

function TableHead({ columns }: { columns: string[] }) { return <div className="table-head">{columns.map(column => <span key={column}>{column}</span>)}</div> }
function EmptyState({ title, body }: { title: string; body: string }) { return <div className="empty"><strong>{title}</strong><p>{body}</p></div> }

export default App
