import { jsPDF } from 'jspdf'

export type BillingPreviewInput = { plan: string; startsOn: string; nextBillingDate: string; organizationName?: string; logoUrl?: string }

/** Sales invoice template matching the approved reference composition. */
export class BillingStatementPdf {
  private async logoData(url?: string): Promise<{ data: string; format: 'PNG' | 'JPEG' | 'SVG' } | undefined> { if (!url) return undefined; try { const response = await fetch(url); if (!response.ok) return undefined; const blob = await response.blob(); const format = blob.type.includes('svg') || url.toLowerCase().split('?')[0].endsWith('.svg') ? 'SVG' : blob.type.includes('jpeg') || blob.type.includes('jpg') ? 'JPEG' : 'PNG'; const data = await new Promise<string | undefined>(resolve => { const reader = new FileReader(); reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : undefined); reader.onerror = () => resolve(undefined); reader.readAsDataURL(blob) }); return data ? { data, format } : undefined } catch { return undefined } }
  private text(pdf: jsPDF, value: string, x: number, y: number, size = 8, bold = false, align?: 'left' | 'center' | 'right'): void { pdf.setFont('helvetica', bold ? 'bold' : 'normal'); pdf.setFontSize(size); pdf.setTextColor(0, 0, 0); pdf.text(value, x, y, align ? { align } : undefined) }
  private band(pdf: jsPDF, x: number, y: number, w: number, h: number, color: [number, number, number]): void { pdf.setFillColor(...color); pdf.rect(x, y, w, h, 'F') }
  private async officialInvoice(title: string, input: BillingPreviewInput, period: string, documentLabel = 'Invoice'): Promise<Blob> {
    const pdf = new jsPDF({ unit: 'mm', format: 'a4' }); pdf.setProperties({ subject: period }); const statement = documentLabel === 'Billing Statement'; const logo = await this.logoData(input.logoUrl); const name = input.organizationName || 'BUSINESS NAME'; const left = 16; const right = 194; const pink: [number, number, number] = [255, 47, 90]; const pale: [number, number, number] = [255, 244, 246]
    pdf.setDrawColor(0, 0, 0); pdf.setLineWidth(0.6); pdf.rect(3, 3, 204, 291)
    if (logo) pdf.addImage(logo.data, logo.format, 24, 18, 34, 32); else { this.band(pdf, 24, 18, 34, 32, [247, 247, 247]); this.text(pdf, 'LOGO', 41, 37, 9, true, 'center') }
    this.text(pdf, documentLabel, right, 29, 24, true, 'right'); this.text(pdf, statement ? 'Statement no.:' : 'Invoice no.:', 122, 40, 7); this.text(pdf, '1', right, 40, 7, false, 'right'); this.text(pdf, statement ? 'Statement date:' : 'Invoice date:', 122, 46, 7); this.text(pdf, new Date().toLocaleDateString(), right, 46, 7, false, 'right'); this.text(pdf, 'Due:', 122, 52, 7); this.text(pdf, input.nextBillingDate || '—', right, 52, 7, false, 'right')
    this.text(pdf, 'From', left, 65, 8, true); this.text(pdf, name, left, 73, 9, true); this.text(pdf, '[OWNER NAME]', left, 81, 7); this.text(pdf, '[E-MAIL]', left, 87, 7); this.text(pdf, '[PHONE]', left, 93, 7); this.text(pdf, '[WEBSITE]', left, 99, 7); this.text(pdf, '[ADDRESS]', left, 105, 7)
    this.text(pdf, 'Bill to', right, 65, 8, true, 'right'); this.text(pdf, 'SUBSCRIBER ACCOUNT', right, 73, 9, true, 'right'); this.text(pdf, '[E-MAIL]', right, 81, 7, false, 'right'); this.text(pdf, '[PHONE]', right, 87, 7, false, 'right'); this.text(pdf, '[ADDRESS]', right, 93, 7, false, 'right'); this.text(pdf, 'Ship to', right, 106, 8, true, 'right'); this.text(pdf, '[SHIPPING ADDRESS]', right, 114, 7, false, 'right'); this.text(pdf, '[TRACKING #]', right, 120, 7, false, 'right')
    this.band(pdf, left, 131, 178, 9, pink); this.text(pdf, 'DESCRIPTION', 19, 137, 6.5, false); this.text(pdf, 'RATE, PHP', 80, 137, 6.5, false); this.text(pdf, 'QTY', 112, 137, 6.5, false); this.text(pdf, 'TAX, %', 127, 137, 6.5, false); this.text(pdf, 'DISC, %', 143, 137, 6.5, false); this.text(pdf, 'AMOUNT, PHP', 174, 137, 6.5, false)
    const rows = [{ name: input.plan || '[ITEM NAME #1]', rate: '1,000.00', qty: '1', tax: '12.0', discount: '0.0', amount: 'Calculated' }, { name: 'Installation fee', rate: '0.00', qty: '1', tax: '12.0', discount: '0.0', amount: 'Calculated' }, { name: title, rate: 'Calculated', qty: '1', tax: '12.0', discount: '0.0', amount: 'Calculated' }]
    rows.forEach((row, index) => { const y = 146 + index * 10; if (index % 2 === 1) this.band(pdf, left, y - 6, 178, 9, pale); this.text(pdf, row.name, 19, y, 7, index === 0); this.text(pdf, row.rate, 80, y, 7); this.text(pdf, row.qty, 113, y, 7); this.text(pdf, row.tax, 128, y, 7); this.text(pdf, row.discount, 144, y, 7); this.text(pdf, row.amount, 193, y, 7, false, 'right') })
    pdf.setDrawColor(120, 120, 120); pdf.line(left, 175, right, 175)
    this.text(pdf, statement ? 'Billing Instructions' : 'Payment Instruction', left, 190, 7.5, true); this.text(pdf, '[ADD INFORMATION ABOUT', left, 197, 7); this.text(pdf, 'YOUR PAYMENT METHOD]', left, 204, 7); this.text(pdf, 'Notes:', left, 235, 7.5, true)
    this.text(pdf, 'Subtotal, PHP:', 104, 190, 7, true); this.text(pdf, '30,000.00', right, 190, 7, true, 'right'); this.text(pdf, 'Discount, PHP:', 104, 197, 7); this.text(pdf, '1,800.00', right, 197, 7, false, 'right'); this.text(pdf, 'Shipping Cost, PHP:', 104, 204, 7); this.text(pdf, '500.00', right, 204, 7, false, 'right'); this.text(pdf, statement ? 'VAT, PHP:' : 'Sales Tax, PHP:', 104, 211, 7); this.text(pdf, '6,150.00', right, 211, 7, false, 'right'); this.text(pdf, 'Total, PHP:', 104, 218, 7, true); this.text(pdf, '34,850.00', right, 218, 7, true, 'right'); this.text(pdf, 'Amount paid, PHP:', 104, 225, 7); this.text(pdf, '0.00', right, 225, 7, false, 'right'); this.band(pdf, 104, 231, 90, 10, pale); this.text(pdf, 'Balance Due, PHP:', 105, 238, 8, true); this.text(pdf, '0.00', right, 238, 8, true, 'right')
    this.text(pdf, 'Client signature', 65, 275, 7, false, 'center'); this.text(pdf, 'Business signature', 145, 275, 7, false, 'center'); this.text(pdf, '[CLIENT NAME]', 65, 282, 7, true, 'center'); this.text(pdf, '[OWNER NAME]', 145, 282, 7, true, 'center')
    return pdf.output('blob')
  }
  newSubscriptionProratedInvoicePreview(input: BillingPreviewInput): Promise<Blob> { return this.officialInvoice('Pro-rated recurring charge', input, 'Start date to cycle end') }
  newSubscriptionFullCycleInvoicePreview(input: BillingPreviewInput): Promise<Blob> { return this.officialInvoice('Full-cycle recurring charge', input, 'Full billing cycle') }
  private async billingStatement(input: BillingPreviewInput, title: string, period: string): Promise<Blob> {
    const pdf = new jsPDF({ unit: 'mm', format: 'a4' }); const logo = await this.logoData(input.logoUrl); const name = input.organizationName || 'ISP Billing'; const teal: [number, number, number] = [23, 145, 132]
    pdf.setFillColor(236, 248, 246); pdf.roundedRect(14, 14, 182, 30, 4, 4, 'F'); if (logo) pdf.addImage(logo.data, logo.format, 20, 19, 30, 20); this.text(pdf, name, 58, 27, 13, true); this.text(pdf, 'BILLING STATEMENT', 190, 25, 12, true, 'right'); this.text(pdf, `Statement date: ${new Date().toLocaleDateString()}`, 190, 33, 7, false, 'right')
    this.text(pdf, 'SUBSCRIBER', 18, 60, 7, true); this.text(pdf, 'Subscriber account', 18, 68, 9, true); this.text(pdf, `Plan: ${input.plan}`, 18, 76, 7); this.text(pdf, `Service starts: ${input.startsOn || '—'}`, 18, 83, 7); this.text(pdf, 'STATEMENT DETAILS', 118, 60, 7, true); this.text(pdf, `Coverage: ${period}`, 118, 68, 7); this.text(pdf, `Next billing date: ${input.nextBillingDate || '—'}`, 118, 76, 7); this.text(pdf, 'Status: Preview', 118, 83, 7)
    this.band(pdf, 18, 96, 174, 9, teal); this.text(pdf, 'CHARGE', 23, 102, 7, true); this.text(pdf, 'DESCRIPTION', 83, 102, 7, true); this.text(pdf, 'AMOUNT (PHP)', 187, 102, 7, true, 'right')
    this.band(pdf, 18, 114, 174, 18, [245, 250, 249]); this.text(pdf, title, 23, 122, 8, true); this.text(pdf, period, 83, 122, 7); this.text(pdf, 'Calculated', 187, 122, 7, false, 'right')
    this.text(pdf, 'Recurring charge', 23, 143, 8, true); this.text(pdf, `Regular ${input.plan} service charge`, 83, 143, 7); this.text(pdf, 'Calculated', 187, 143, 7, false, 'right'); pdf.setDrawColor(...teal); pdf.line(18, 151, 192, 151)
    this.text(pdf, 'STATEMENT SUMMARY', 18, 166, 8, true); this.text(pdf, 'Subtotal', 125, 166, 8); this.text(pdf, 'Calculated', 187, 166, 8, false, 'right'); this.text(pdf, 'VAT', 125, 175, 8); this.text(pdf, 'Calculated', 187, 175, 8, false, 'right'); pdf.setFillColor(236, 248, 246); pdf.roundedRect(120, 183, 72, 18, 3, 3, 'F'); this.text(pdf, 'TOTAL AMOUNT DUE', 124, 191, 7, true); this.text(pdf, 'Calculated', 187, 191, 8, true, 'right')
    this.text(pdf, 'Billing instructions', 18, 215, 8, true); this.text(pdf, 'This statement is a preview of the upcoming billing cycle.', 18, 223, 7); this.text(pdf, 'Amounts are finalized when the billing statement is issued.', 18, 230, 7); this.text(pdf, 'Preview only — not an issued invoice.', 18, 270, 7, false); this.text(pdf, `Generated ${new Date().toLocaleString()}`, 192, 270, 7, false, 'right'); return pdf.output('blob')
  }
  newSubscriptionProratedBillingStatement(input: BillingPreviewInput): Promise<Blob> { return this.billingStatement(input, 'Pro-rated recurring charge', 'Start date to cycle end') }
  newSubscriptionFullCycleBillingStatement(input: BillingPreviewInput): Promise<Blob> { return this.billingStatement(input, 'Full-cycle recurring charge', 'Full billing cycle') }
  open(blob: Blob): void { const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000) }
}
